name: App Build

on:
  push:
    branches:
      - build
  workflow_dispatch:

env:
  APP_NAME: ezops-api
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
          ref: ${{github.base_ref}}

    - name: Build NPM
      run: |
        docker run \
        -v $(pwd):/app \
        -w /app \
        --rm \
        node:14.21.3-slim \
        /bin/sh -c "npm install && npm run build"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Sync to S3
      run: aws s3 sync ./dist s3://$BUCKET_NAME --delete